repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
      - id: shellcheck
        args: [--severity=warning]
  - repo: https://github.com/mvdan/shfmt
    rev: v3.8.0
    hooks:
      - id: shfmt
        args: [-i, 4, -fn, -w]
        types: [shell]
